const state = {
	active: 'active',
	activeUnselected: 'activeUnselected',
	disable: 'disable',
	success: 'success',
	successActive: 'successActive',
}

const stateCss = {
	active: {
		background: 'var(--primary-blue-primary-blue-900)',
		border: '2px solid var(--secundary-accent-secundary-accent-main-500)',
	},
	disable: {
		background: 'var(--neutral-gray-colors-neutral-gray-300)',
		border: 'none',
	},
	success: {
		background: 'none',
		border: '2px solid var(--neutral-gray-colors-neutral-gray-300)',
	},
	successActive: {
		background: 'var(--primary-blue-primary-blue-900)',
		border: '2px solid var(--secundary-accent-secundary-accent-main-500)',
	},
}

const stateAfterBefore = {
	active: {
		background: 'var(--secundary-accent-secundary-accent-main-500)',
		height: '26px',
	},
	activeUnselected: {
		background: 'var(--secundary-accent-secundary-accent-main-500)',
		height: '26px',
	},
	disable: {
		background: 'var(--neutral-gray-colors-neutral-white)',
		height: '26px',
	},
	success: {
		background: 'var(--secundary-accent-secundary-accent-main-500)',
		height: '26px',
	},
	successActive: {
		background: 'var(--secundary-accent-secundary-accent-main-500)',
		height: '26px',
	},
}

const planState = {
	mensual: 'mensual',
	anual: 'anual',
	trimestral: 'trimestral',
	semestral: 'semestral',
}
const position = {
	top: 'top',
	bottom: 'bottom',
	left: 'left',
	right: 'right',
	mid: 'mid',
	topMid: 'topMid',
	topRight: 'topRight',
	topLeft: 'topLeft',
	bottomMid: 'bottomMid',
	bottomRight: 'bottomRight',
	bottomLeft: 'bottomLeft',
	leftMid: 'leftMid',
	leftTop: 'leftTop',
	leftBottom: 'leftBottom',
	rightMid: 'rightMid',
	rightTop: 'rightTop',
	rightBottom: 'rightBottom',
	center: 'center',
}
const tipoIdentificacion = [
	{ value: '1', label: 'Cedula de nacional' },
	{ value: '2', label: 'Dimex' },
	{ value: '3', label: 'Pasaporte' },
]
const generos = [
	{ value: 'M', label: 'Masculino' },
	{ value: 'F', label: 'Femenino' },
	{ value: 'S', label: 'Sin Especificar' },
]

const provinciasCostarica = [
	{ value: '1', label: 'San José' },
	{ value: '2', label: 'Alajuela' },
	{ value: '3', label: 'Cartago' },
	{ value: '4', label: 'Heredia' },
	{ value: '5', label: 'Guanacaste' },
	{ value: '6', label: 'Puntarenas' },
	{ value: '7', label: 'Limón' },
]
const cantonesCostarica = [
	{ value: '1', label: 'San José' },
	{ value: '1', label: 'Escazu' },
	{ value: '1', label: 'Desamparados' },
	{ value: '1', label: 'Puriscal' },
	{ value: '1', label: 'Tarrazu' },
	{ value: '1', label: 'Aserrí' },
	{ value: '1', label: 'Mora' },
	{ value: '1', label: 'Goicoechea' },
	{ value: '1', label: 'Santa Ana' },
	{ value: '1', label: 'Alajuelita' },
	{ value: '1', label: 'Vázquez de Coronado' },
	{ value: '1', label: 'Acosta' },
	{ value: '1', label: 'Tibás' },
	{ value: '1', label: 'Moravia' },
	{ value: '1', label: 'Montes de Oca' },
	{ value: '1', label: 'Turrubares' },
	{ value: '1', label: 'Dota' },
	{ value: '1', label: 'Curridabat' },
	{ value: '1', label: 'Pérez Zeledón' },
	{ value: '1', label: 'León Cortés' },
	{ value: '2', label: 'Alajuela' },
	{ value: '2', label: 'San Ramón' },
	{ value: '2', label: 'Grecia' },
	{ value: '2', label: 'San Mateo' },
	{ value: '2', label: 'Atenas' },
	{ value: '2', label: 'Naranjo' },
	{ value: '2', label: 'Palmares' },
	{ value: '2', label: 'Poás' },
	{ value: '2', label: 'Orotina' },
	{ value: '2', label: 'San Carlos' },
	{ value: '2', label: 'Zarcero' },
	{ value: '2', label: 'Valverde Vega' },
	{ value: '2', label: 'Upala' },
	{ value: '2', label: 'Los Chiles' },
	{ value: '2', label: 'Guatuso' },
	{ value: '2', label: 'Río Cuarto' },
	{ value: '3', label: 'Cartago' },
	{ value: '3', label: 'Paraíso' },
	{ value: '3', label: 'La Unión' },
	{ value: '3', label: 'Jiménez' },
	{ value: '3', label: 'Turrialba' },
	{ value: '3', label: 'Alvarado' },
	{ value: '3', label: 'Oreamuno' },
	{ value: '3', label: 'El Guarco' },
	{ value: '4', label: 'Heredia' },
	{ value: '4', label: 'Barva' },
	{ value: '4', label: 'Santo Domingo' },
	{ value: '4', label: 'Santa Bárbara' },
	{ value: '4', label: 'San Rafael' },
	{ value: '4', label: 'San Isidro' },
	{ value: '4', label: 'Belén' },
	{ value: '4', label: 'Flores' },
	{ value: '4', label: 'San Pablo' },
	{ value: '4', label: 'Sarapiquí' },
	{ value: '5', label: 'Liberia' },
	{ value: '5', label: 'Nicoya' },
	{ value: '5', label: 'Santa Cruz' },
	{ value: '5', label: 'Bagaces' },
	{ value: '5', label: 'Carrillo' },
	{ value: '5', label: 'Cañas' },
	{ value: '5', label: 'Abangares' },
	{ value: '5', label: 'Tilarán' },
	{ value: '5', label: 'Nandayure' },
	{ value: '5', label: 'La Cruz' },
	{ value: '5', label: 'Hojancha' },
	{ value: '6', label: 'Puntarenas' },
	{ value: '6', label: 'Esparza' },
	{ value: '6', label: 'Buenos Aires' },
	{ value: '6', label: 'Montes de Oro' },
	{ value: '6', label: 'Osa' },
	{ value: '6', label: 'Quepos' },
	{ value: '6', label: 'Golfito' },
	{ value: '6', label: 'Coto Brus' },
	{ value: '6', label: 'Parrita' },
	{ value: '6', label: 'Corredores' },
	{ value: '6', label: 'Garabito' },
	{ value: '7', label: 'Limón' },
	{ value: '7', label: 'Pococí' },
	{ value: '7', label: 'Siquirres' },
	{ value: '7', label: 'Talamanca' },
	{ value: '7', label: 'Matina' },
	{ value: '7', label: 'Guácimo' },
]
const districtCostarica = [
	{ value: '1', label: 'San José' },
	{ value: '1', label: 'Escazu' },
	{ value: '1', label: 'Desamparados' },
	{ value: '1', label: 'Puriscal' },
	{ value: '1', label: 'Tarrazu' },
	{ value: '1', label: 'Aserrí' },
	{ value: '1', label: 'Mora' },
	{ value: '1', label: 'Goicoechea' },
	{ value: '1', label: 'Santa Ana' },
	{ value: '1', label: 'Alajuelita' },
	{ value: '1', label: 'Vázquez de Coronado' },
	{ value: '1', label: 'Acosta' },
	{ value: '1', label: 'Tibás' },
	{ value: '1', label: 'Moravia' },
	{ value: '1', label: 'Montes de Oca' },
	{ value: '1', label: 'Turrubares' },
	{ value: '1', label: 'Dota' },
	{ value: '1', label: 'Curridabat' },
	{ value: '1', label: 'Pérez Zeledón' },

	{ value: '2', label: 'Alajuela' },
	{ value: '2', label: 'San Ramón' },
	{ value: '2', label: 'Grecia' },
	{ value: '2', label: 'San Mateo' },
	{ value: '2', label: 'Atenas' },
	{ value: '2', label: 'Naranjo' },
	{ value: '2', label: 'Palmares' },
	{ value: '2', label: 'Poás' },
	{ value: '2', label: 'Orotina' },
	{ value: '2', label: 'San Carlos' },
	{ value: '2', label: 'Zarcero' },
	{ value: '2', label: 'Valverde Vega' },
]
export {
	state,
	stateCss,
	stateAfterBefore,
	planState,
	position,
	tipoIdentificacion,
	generos,
	provinciasCostarica,
	cantonesCostarica,
	districtCostarica
}
