import Andorra from '@/assets/img/countries/AD/country.png'
import UnitedArabEmirates from '@/assets/img/countries/AE/country.png'
import Afghanistan from '@/assets/img/countries/AF/country.png'
import AntiguaAndBarbuda from '@/assets/img/countries/AG/country.png'
import Anguilla from '@/assets/img/countries/AI/country.png'
import Albania from '@/assets/img/countries/AL/country.png'
import Armenia from '@/assets/img/countries/AM/country.png'
import Angola from '@/assets/img/countries/AO/country.png'
import Antarctica from '@/assets/img/countries/AQ/country.png'
import Argentina from '@/assets/img/countries/AR/country.png'
import AmericanSamoa from '@/assets/img/countries/AS/country.png'
import Austria from '@/assets/img/countries/AT/country.png'
import Australia from '@/assets/img/countries/AU/country.png'
import Aruba from '@/assets/img/countries/AW/country.png'
import AlandIslands from '@/assets/img/countries/AX/country.png'
import Azerbaijan from '@/assets/img/countries/AZ/country.png'
import BosniaAndHerzegovina from '@/assets/img/countries/BA/country.png'
import Barbados from '@/assets/img/countries/BB/country.png'
import Bangladesh from '@/assets/img/countries/BD/country.png'
import Belgium from '@/assets/img/countries/BE/country.png'
import BurkinaFaso from '@/assets/img/countries/BF/country.png'
import Bulgaria from '@/assets/img/countries/BG/country.png'
import Bahrain from '@/assets/img/countries/BH/country.png'
import Burundi from '@/assets/img/countries/BI/country.png'
import Benin from '@/assets/img/countries/BJ/country.png'



