import Head from 'next/head'
import styled from 'styled-components'
import CMP020 from '@/components/home/CMP020'

//bg background index
//gd gradient state
const Layout = () => {

	return (
		<>
    
			<Head>
				<title>vb</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
				
			<header>
				
		
			</header>
			<section>
				<aside>
					<CMP020/>q
            
				</aside>

			</section>

					
			
			<footer>® Derechos reservados - Medismart 2023</footer>

		</>
	)
}
export default Layout


