import Head from 'next/head'
import styled from 'styled-components'
import Contenedor_Menu from '@/components/sideMenu/Contenedor_Menu'
import CMP017 from '@/components/header/CMP017'
import { useSelector } from 'react-redux'
import ModalContainer from '../common/ModalContainer'
import { useEffect, useState } from 'react'
import Bienvenida from '../modalContents/Bienvenida'
import { setWelcomeModal } from '@/store/slices/configSlice'
import { useDispatch } from 'react-redux'
import { setFlags } from '@/store/slices/storageSlice'
import data from '@/data/countries.json'
import usePage from '@/hooks/usePage'
import PoliticaDePrivacidad from '../common/PoliticaDePrivacidad'
const Layout = ({ children }) => {
	const { welcomeModal, currentIndex } = useSelector((state) => state.config)
	// const { flagData } = useSelector((state) => state.storage)
	const [showModal, setShowModal] = useState(true)
	const dispatch = useDispatch()
	const { goTo } = usePage()
	useEffect(() => {
		if (welcomeModal && showModal) {
			goTo('/', () => {
				dispatch(setWelcomeModal(true))
			})
		}

		const transformedData = data?.map((country) => {
			//validate if country.idd has suffixes, if not, return null
			let suffixes = country.idd.suffixes ? country.idd.suffixes[0] : ''
			let root = country.idd.root ?? ''
			let countryCode = country.car.signs ? country.car.signs[0] : ''
			let src = country.flags.png ?? ''
			let name = country.translations.spa.common ?? ''
			return {
				src,
				name,
				countryCode,
				codeArea: root + suffixes,
			}
		})
		dispatch(setFlags(transformedData))
	}, [data])
	const funcOnClose = () => {
		dispatch(setWelcomeModal(false))
	}
	return (
		<>
			<Head>
				<title>AutoAfiliacion</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout currentIndex={currentIndex}>
				<header>
					<CMP017 />
				</header>
				<section>
					<aside>
						<Contenedor_Menu />
					</aside>
					<article>{children}</article>
				</section>
				{welcomeModal && showModal && (
					<ModalContainer
						title="¡Hola, que bueno verte por acá!"
						showModal={showModal}
						setModal={setShowModal}
						funcOnClose={funcOnClose}
					>
						<Bienvenida />
					</ModalContainer>
				)}
				
				<footer>® Derechos reservados - Medismart 2023</footer>
			</MainLayout>
		</>
	)
}
export default Layout

const MainLayout = styled.main`
  box-sizing: border-box;
  display: grid;
  grid-template-rows: calc(48px + 80px) 1fr 80px;
  grid-template-columns: 1fr minmax(330px, 1440px) 1fr;
  grid-template-areas:
    "header header header"
    "content content content"
    "footer footer footer";
  min-height: 100vh;
  min-width: 100%;
  padding: 48px 56px 0 56px;
  & > header {
    grid-column: 2/3;
  }
  & > section {
    display: grid;
    grid-template-columns: 314px 1fr;
    grid-column: 2/3;
    grid-template-areas: "menu article";
    box-shadow: 0px 4px 4px rgba(192, 200, 214, 0.25);
    border-radius: 10px;
    position: relative;
    overflow: hidden;
    place-content: center;
    background-color: ${(props) =>
		props.currentIndex !== 1
			? ' var(--neutral-background-neutral-olive-100)'
			: 'var(--neutral-gray-colors-neutral-white)'};
  }
  & > article {
    grid-area: article;
  }
  & > aside {
    grid-area: menu;
  }
  & > footer {
    grid-area: footer;
    background-color: #ffffff;
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: Montserrat;
    font-size: 14px;
    font-weight: 500;
    line-height: 17px;
    letter-spacing: 0px;
    text-align: center;
  }

  @media (max-width: 1194px) {
    padding: 48px 46px 0 46px;
    & > section {
      display: flex;
      flex-direction: column;
      padding: 10px;
      box-shadow: none;
      & > article {
        box-shadow: 0px 4px 4px rgba(192, 200, 214, 0.25);
      }
    }
  }
`
